---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: prometheus
    spec:
      destination:
        name: "{{cluster}}"
        namespace: prometheus
      project: default
      source:
        path: cluster-resources/prometheus-operator
        repoURL: https://github.com/dormstd/k8s-homelab.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true